export const RELATED_LINKS = [
  { label: "Email Attachment Size", href: "https://www.emailattachmentsize.com" },
  { label: "Debt Reducing Calculator", href: "https://www.debtreducingcalculator.com" },
  { label: "YouTube Title Checker", href: "https://www.youtubetitlechecker.com" },
  { label: "High Yield Savings Calculator", href: "https://www.highyieldsavingscalculator.com" },
  { label: "Life Insurance Coverage Calculator", href: "https://www.lifeinsurancecoveragecalculator.com" },
  { label: "Subscription Cost Tracker", href: "https://www.mysubscriptioncost.com" },
  { label: "GPA Calculator", href: "https://www.my-gpacalculator.com" },
  { label: "Credit Card Payoff Calculator", href: "https://www.creditcarddebtpayoffcalculator.com" },
  { label: "Cool Username Generator", href: "https://www.coolusernamegenerator.com" },
  { label: "Freelancer Rates Calculator", href: "https://www.freelancerratescalculator.com" },
  { label: "Emergency Savings Calculator", href: "https://www.emergencysavingscalculator.com" },
  { label: "Side Hustle Tax Estimator", href: "https://www.sidehustletaxestimator.com" },
  { label: "Retirement Savings Gap", href: "https://www.retirementsavingsgap.com" },
  { label: "Online Course ROI", href: "https://www.onlinecourseroi.com" },
  { label: "Strong Password Builder", href: "https://www.strongpasswordbuilder.com" },
  { label: "Mortgage Affordability Estimator", href: "https://www.mortgageaffordabilityestimator.com" },
  { label: "Moneywise Calculators", href: "https://www.moneywisecalculator.com" },
  { label: "Stop Trial Billing", href: "https://www.stoptrialbilling.com" },
  { label: "Capital Gains Tax Calculator", href: "https://www.investmentgainstaxcalc.com" },
  { label: "Roth vs Traditional IRA", href: "https://www.rothvstraditional.com" },
  { label: "Rent vs Buy Estimator", href: "https://www.rentvsbuyestimator.com" },
  { label: "CD Penalty Calculator", href: "https://www.cdpenaltycalc.com" }
];