export const metadata = {
  title: "Privacy Policy | Strong Password Builder",
  description: "Privacy policy for Strong Password Builder. Learn how we handle data, cookies, and third-party services including Google AdSense and Google Analytics.",
  robots: { index: true, follow: true },
};

export default function PrivacyPage() {
  return (
    <main style={{ maxWidth: "780px", margin: "0 auto", padding: "2rem 1.5rem", fontFamily: "'DM Mono', monospace", color: "#1a1a1a", background: "#faf8f4", minHeight: "100vh" }}>
      <p style={{ fontSize: "12px", marginBottom: "1.5rem" }}>
        <a href="/" style={{ color: "#2d6a4f", textDecoration: "none" }}>&#8592; Back to Strong Password Builder</a>
      </p>

      <h1 style={{ fontFamily: "Georgia, serif", fontSize: "2rem", marginBottom: ".5rem" }}>Privacy Policy</h1>
      <p style={{ fontSize: "12px", color: "#888", marginBottom: "2rem" }}>Last updated: May 19, 2026</p>

      <section style={{ marginBottom: "2rem" }}>
        <h2 style={{ fontSize: "1rem", fontWeight: "600", marginBottom: ".75rem" }}>About this site</h2>
        <p style={{ fontSize: "13px", lineHeight: "1.8", color: "#444" }}>
          Strong Password Builder (strongpasswordbuilder.com) is a free tool that generates cryptographically random passwords entirely within your browser. It is operated by MoneyWise Calculators, a network of free online tools. This privacy policy explains what information is collected when you use this site, how it is used, and your rights regarding that information.
        </p>
      </section>

      <section style={{ marginBottom: "2rem" }}>
        <h2 style={{ fontSize: "1rem", fontWeight: "600", marginBottom: ".75rem" }}>Information we do not collect</h2>
        <p style={{ fontSize: "13px", lineHeight: "1.8", color: "#444" }}>
          We do not collect, store, or transmit any passwords generated by this tool. All password generation happens entirely within your browser using your device's built-in cryptographic random number generator. No passwords, settings, or inputs are ever sent to our servers or any third party. We do not require you to create an account or provide an email address to use this tool.
        </p>
      </section>

      <section style={{ marginBottom: "2rem" }}>
        <h2 style={{ fontSize: "1rem", fontWeight: "600", marginBottom: ".75rem" }}>Cookies</h2>
        <p style={{ fontSize: "13px", lineHeight: "1.8", color: "#444" }}>
          This site uses cookies. Cookies are small text files stored on your device by your browser. We use cookies for the following purposes:
        </p>
        <ul style={{ fontSize: "13px", lineHeight: "1.9", color: "#444", paddingLeft: "1.5rem", marginTop: ".75rem" }}>
          <li><strong>Analytics cookies</strong> -- placed by Google Analytics to help us understand how visitors use the site (pages visited, time on site, general geographic region). This data is aggregated and anonymous.</li>
          <li><strong>Advertising cookies</strong> -- placed by Google AdSense to serve relevant advertisements. These cookies may track your browsing across websites to show you ads that match your interests.</li>
        </ul>
        <p style={{ fontSize: "13px", lineHeight: "1.8", color: "#444", marginTop: ".75rem" }}>
          You can control or disable cookies through your browser settings. Disabling cookies will not prevent you from using the tool, but may affect how advertisements are displayed.
        </p>
      </section>

      <section style={{ marginBottom: "2rem" }}>
        <h2 style={{ fontSize: "1rem", fontWeight: "600", marginBottom: ".75rem" }}>Google AdSense</h2>
        <p style={{ fontSize: "13px", lineHeight: "1.8", color: "#444" }}>
          This site displays advertisements served by Google AdSense, a service provided by Google LLC. Google AdSense uses cookies and similar tracking technologies to serve ads based on your prior visits to this website and other websites. Google's use of advertising cookies enables it and its partners to serve ads based on your visit to this site and other sites on the internet.
        </p>
        <p style={{ fontSize: "13px", lineHeight: "1.8", color: "#444", marginTop: ".75rem" }}>
          You may opt out of personalized advertising by visiting{" "}
          <a href="https://www.google.com/settings/ads" style={{ color: "#2d6a4f" }} target="_blank" rel="noopener noreferrer">Google Ads Settings</a>.
          For more information on how Google uses data from sites that use its advertising services, visit{" "}
          <a href="https://policies.google.com/technologies/partner-sites" style={{ color: "#2d6a4f" }} target="_blank" rel="noopener noreferrer">How Google uses information from sites or apps that use our services</a>.
        </p>
      </section>

      <section style={{ marginBottom: "2rem" }}>
        <h2 style={{ fontSize: "1rem", fontWeight: "600", marginBottom: ".75rem" }}>Google Analytics</h2>
        <p style={{ fontSize: "13px", lineHeight: "1.8", color: "#444" }}>
          This site uses Google Analytics to collect anonymous information about how visitors use the site. Google Analytics collects information such as how often users visit the site, what pages they visit, and what other sites they used prior to visiting. We use this information to improve the site. Google Analytics collects only the IP address assigned to you on the date you visit, not your name or other personally identifying information.
        </p>
        <p style={{ fontSize: "13px", lineHeight: "1.8", color: "#444", marginTop: ".75rem" }}>
          You can prevent Google Analytics from recognizing you on return visits by disabling cookies in your browser, or by installing the{" "}
          <a href="https://tools.google.com/dlpage/gaoptout" style={{ color: "#2d6a4f" }} target="_blank" rel="noopener noreferrer">Google Analytics Opt-out Browser Add-on</a>.
        </p>
      </section>

      <section style={{ marginBottom: "2rem" }}>
        <h2 style={{ fontSize: "1rem", fontWeight: "600", marginBottom: ".75rem" }}>Third-party links</h2>
        <p style={{ fontSize: "13px", lineHeight: "1.8", color: "#444" }}>
          This site contains links to other websites in the MoneyWise Calculators network and to external resources. We are not responsible for the privacy practices of those sites. We encourage you to review the privacy policies of any third-party sites you visit.
        </p>
      </section>

      <section style={{ marginBottom: "2rem" }}>
        <h2 style={{ fontSize: "1rem", fontWeight: "600", marginBottom: ".75rem" }}>Your rights</h2>
        <p style={{ fontSize: "13px", lineHeight: "1.8", color: "#444" }}>
          Because we do not collect personal information directly, we do not hold personal data that can be accessed, corrected, or deleted on request. For data held by Google through AdSense or Analytics, you can manage your preferences through{" "}
          <a href="https://myaccount.google.com" style={{ color: "#2d6a4f" }} target="_blank" rel="noopener noreferrer">Google Account settings</a>.
        </p>
      </section>

      <section style={{ marginBottom: "2rem" }}>
        <h2 style={{ fontSize: "1rem", fontWeight: "600", marginBottom: ".75rem" }}>Changes to this policy</h2>
        <p style={{ fontSize: "13px", lineHeight: "1.8", color: "#444" }}>
          We may update this privacy policy from time to time. Changes will be posted on this page with an updated date. Continued use of the site after any changes constitutes acceptance of the updated policy.
        </p>
      </section>

      <section style={{ marginBottom: "2rem" }}>
        <h2 style={{ fontSize: "1rem", fontWeight: "600", marginBottom: ".75rem" }}>Contact</h2>
        <p style={{ fontSize: "13px", lineHeight: "1.8", color: "#444" }}>
          For privacy-related questions, you can reach us through{" "}
          <a href="https://moneywisecalculator.com" style={{ color: "#2d6a4f" }}>MoneyWise Calculator</a>.
        </p>
      </section>

      <p style={{ fontSize: "12px", color: "#aaa", borderTop: "1px solid #e0dbd3", paddingTop: "1.5rem" }}>
        &copy; 2026 MoneyWise Calculators &middot; <a href="/terms" style={{ color: "#aaa" }}>Terms of Service</a>
      </p>
    </main>
  );
}
