export const metadata = {
  title: "Terms of Service | Strong Password Builder",
  description: "Terms of service for Strong Password Builder. Please read these terms before using the tool.",
  robots: { index: true, follow: true },
};

export default function TermsPage() {
  return (
    <main style={{ maxWidth: "780px", margin: "0 auto", padding: "2rem 1.5rem", fontFamily: "'DM Mono', monospace", color: "#1a1a1a", background: "#faf8f4", minHeight: "100vh" }}>
      <p style={{ fontSize: "12px", marginBottom: "1.5rem" }}>
        <a href="/" style={{ color: "#2d6a4f", textDecoration: "none" }}>&#8592; Back to Strong Password Builder</a>
      </p>

      <h1 style={{ fontFamily: "Georgia, serif", fontSize: "2rem", marginBottom: ".5rem" }}>Terms of Service</h1>
      <p style={{ fontSize: "12px", color: "#888", marginBottom: "2rem" }}>Last updated: May 19, 2026</p>

      <section style={{ marginBottom: "2rem" }}>
        <h2 style={{ fontSize: "1rem", fontWeight: "600", marginBottom: ".75rem" }}>Acceptance of terms</h2>
        <p style={{ fontSize: "13px", lineHeight: "1.8", color: "#444" }}>
          By accessing or using Strong Password Builder at strongpasswordbuilder.com, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the site. These terms apply to all visitors and users of the site.
        </p>
      </section>

      <section style={{ marginBottom: "2rem" }}>
        <h2 style={{ fontSize: "1rem", fontWeight: "600", marginBottom: ".75rem" }}>Description of service</h2>
        <p style={{ fontSize: "13px", lineHeight: "1.8", color: "#444" }}>
          Strong Password Builder is a free online tool that generates cryptographically random passwords within the user's browser. Users can customize password length and character types. All generation happens client-side — no passwords or inputs are transmitted to any server.
        </p>
      </section>

      <section style={{ marginBottom: "2rem" }}>
        <h2 style={{ fontSize: "1rem", fontWeight: "600", marginBottom: ".75rem" }}>No security guarantee</h2>
        <p style={{ fontSize: "13px", lineHeight: "1.8", color: "#444" }}>
          While this tool uses your browser's built-in cryptographic random number generator and follows established best practices for password generation, we make no guarantee that any password generated by this tool will be immune to all forms of attack. Password security also depends on how passwords are stored, transmitted, and used. You are responsible for using passwords generated by this tool in a secure manner.
        </p>
        <p style={{ fontSize: "13px", lineHeight: "1.8", color: "#444", marginTop: ".75rem" }}>
          We strongly recommend storing generated passwords in a reputable password manager and enabling two-factor authentication on all accounts where it is available.
        </p>
      </section>

      <section style={{ marginBottom: "2rem" }}>
        <h2 style={{ fontSize: "1rem", fontWeight: "600", marginBottom: ".75rem" }}>No professional advice</h2>
        <p style={{ fontSize: "13px", lineHeight: "1.8", color: "#444" }}>
          Nothing on this site constitutes professional security, legal, or technical advice. The tool and all accompanying content are provided for general informational purposes only. For specific security requirements — particularly for enterprise, government, or regulated environments — consult a qualified security professional.
        </p>
      </section>

      <section style={{ marginBottom: "2rem" }}>
        <h2 style={{ fontSize: "1rem", fontWeight: "600", marginBottom: ".75rem" }}>Acceptable use</h2>
        <p style={{ fontSize: "13px", lineHeight: "1.8", color: "#444" }}>
          You may use this tool for personal, educational, or commercial purposes. You agree not to:
        </p>
        <ul style={{ fontSize: "13px", lineHeight: "1.9", color: "#444", paddingLeft: "1.5rem", marginTop: ".75rem" }}>
          <li>Use the site in any way that violates applicable laws or regulations</li>
          <li>Attempt to disrupt, overload, or interfere with the site's infrastructure</li>
          <li>Use automated tools to systematically access the site at a rate that impairs normal use by others</li>
          <li>Use this tool to generate passwords for unauthorized access to systems or accounts you do not own</li>
        </ul>
      </section>

      <section style={{ marginBottom: "2rem" }}>
        <h2 style={{ fontSize: "1rem", fontWeight: "600", marginBottom: ".75rem" }}>Intellectual property</h2>
        <p style={{ fontSize: "13px", lineHeight: "1.8", color: "#444" }}>
          The content, design, text, and code of this site are owned by MoneyWise Calculators and are protected by applicable copyright and intellectual property laws. You may not reproduce, distribute, or create derivative works from the site's content without express written permission.
        </p>
      </section>

      <section style={{ marginBottom: "2rem" }}>
        <h2 style={{ fontSize: "1rem", fontWeight: "600", marginBottom: ".75rem" }}>Disclaimer of warranties</h2>
        <p style={{ fontSize: "13px", lineHeight: "1.8", color: "#444" }}>
          This site and its tool are provided "as is" and "as available" without warranties of any kind, either express or implied. We do not warrant that the site will be uninterrupted, error-free, or free of viruses or other harmful components.
        </p>
      </section>

      <section style={{ marginBottom: "2rem" }}>
        <h2 style={{ fontSize: "1rem", fontWeight: "600", marginBottom: ".75rem" }}>Limitation of liability</h2>
        <p style={{ fontSize: "13px", lineHeight: "1.8", color: "#444" }}>
          To the fullest extent permitted by law, MoneyWise Calculators and its operators shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of, or inability to use, this site or tool. This includes any security breach, unauthorized access, or data loss resulting from use of passwords generated by this tool.
        </p>
      </section>

      <section style={{ marginBottom: "2rem" }}>
        <h2 style={{ fontSize: "1rem", fontWeight: "600", marginBottom: ".75rem" }}>Third-party services and advertising</h2>
        <p style={{ fontSize: "13px", lineHeight: "1.8", color: "#444" }}>
          This site displays advertisements through Google AdSense and uses Google Analytics for traffic measurement. Your interaction with these services is governed by Google's own terms of service and privacy policies. We are not responsible for the content of third-party advertisements or the practices of third-party services.
        </p>
      </section>

      <section style={{ marginBottom: "2rem" }}>
        <h2 style={{ fontSize: "1rem", fontWeight: "600", marginBottom: ".75rem" }}>Changes to these terms</h2>
        <p style={{ fontSize: "13px", lineHeight: "1.8", color: "#444" }}>
          We reserve the right to modify these terms at any time. Updated terms will be posted on this page with a revised date. Your continued use of the site after any changes constitutes your acceptance of the updated terms.
        </p>
      </section>

      <section style={{ marginBottom: "2rem" }}>
        <h2 style={{ fontSize: "1rem", fontWeight: "600", marginBottom: ".75rem" }}>Governing law</h2>
        <p style={{ fontSize: "13px", lineHeight: "1.8", color: "#444" }}>
          These terms are governed by the laws of the United States. Any disputes arising from use of this site shall be subject to the jurisdiction of the applicable courts.
        </p>
      </section>

      <section style={{ marginBottom: "2rem" }}>
        <h2 style={{ fontSize: "1rem", fontWeight: "600", marginBottom: ".75rem" }}>Contact</h2>
        <p style={{ fontSize: "13px", lineHeight: "1.8", color: "#444" }}>
          For questions about these terms, contact us through{" "}
          <a href="https://moneywisecalculator.com" style={{ color: "#2d6a4f" }}>MoneyWise Calculator</a>.
        </p>
      </section>

      <p style={{ fontSize: "12px", color: "#aaa", borderTop: "1px solid #e0dbd3", paddingTop: "1.5rem" }}>
        &copy; 2026 MoneyWise Calculators &middot; <a href="/privacy" style={{ color: "#aaa" }}>Privacy Policy</a>
      </p>
    </main>
  );
}
